<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration>
    <connections>
        <color>0x8099ffff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module7</idModule>
            <name>oscillo_in</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module5</idModule>
            <name>vcf_output</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0xcc3333ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module3</idModule>
            <name>sequencer_gate</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module1</idModule>
            <name>outputAmplitude</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0x001a80ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module5</idModule>
            <name>vcf_input</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module2</idModule>
            <name>outputAmplitude</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0xcc3333ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module4</idModule>
            <name>mixer_input1</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module3</idModule>
            <name>sequencer_out</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0xcc3333ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module0</idModule>
            <name>out_input</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module7</idModule>
            <name>oscillo_out</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0xe6e64dff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module2</idModule>
            <name>vco_inputFm</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module4</idModule>
            <name>output</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0x003300ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module4</idModule>
            <name>mixer_input0</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module6</idModule>
            <name>outputKeyCV</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <modules>
        <filename>fxml/out.fxml</filename>
        <id>Module0</id>
        <parameters>
            <entry>
                <key>muteVolumeFx</key>
                <value>1.0</value>
            </entry>
            <entry>
                <key>knobVolume</key>
                <value>-23.851458841007577</value>
            </entry>
        </parameters>
        <ports>
            <connected>true</connected>
            <name>out_input</name>
            <type>IN</type>
        </ports>
        <posX>0</posX>
        <posY>0</posY>
    </modules>
    <modules>
        <filename>fxml/vco.fxml</filename>
        <id>Module1</id>
        <parameters>
            <entry>
                <key>octave</key>
                <value>5.0</value>
            </entry>
            <entry>
                <key>typeOutput</key>
                <value>1.0</value>
            </entry>
            <entry>
                <key>precision</key>
                <value>-0.8128810695443728</value>
            </entry>
            <entry>
                <key>choiceBaseFreq</key>
                <value>1.0</value>
            </entry>
            <entry>
                <key>choiceAmplitude</key>
                <value>1.0</value>
            </entry>
        </parameters>
        <ports>
            <connected>false</connected>
            <name>vco_inputFm</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputf0</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputOctave</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputSelectShape</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputAmplitude</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>outputAmplitude</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputSquare</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputSawTooth</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputTriangle</name>
            <type>OUT</type>
        </ports>
        <posX>0</posX>
        <posY>1</posY>
    </modules>
    <modules>
        <filename>fxml/vco.fxml</filename>
        <id>Module2</id>
        <parameters>
            <entry>
                <key>octave</key>
                <value>4.0</value>
            </entry>
            <entry>
                <key>typeOutput</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>precision</key>
                <value>0.29956513229648163</value>
            </entry>
            <entry>
                <key>choiceBaseFreq</key>
                <value>2.0</value>
            </entry>
            <entry>
                <key>choiceAmplitude</key>
                <value>1.0</value>
            </entry>
        </parameters>
        <ports>
            <connected>true</connected>
            <name>vco_inputFm</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputf0</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputOctave</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputSelectShape</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputAmplitude</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>outputAmplitude</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputSquare</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputSawTooth</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputTriangle</name>
            <type>OUT</type>
        </ports>
        <posX>1</posX>
        <posY>1</posY>
    </modules>
    <modules>
        <filename>fxml/seq.fxml</filename>
        <id>Module3</id>
        <parameters>
            <entry>
                <key>knob7</key>
                <value>-0.4166666666666667</value>
            </entry>
            <entry>
                <key>knob6</key>
                <value>-0.0</value>
            </entry>
            <entry>
                <key>knob5</key>
                <value>0.3333333333333333</value>
            </entry>
            <entry>
                <key>knob4</key>
                <value>0.5833333333333334</value>
            </entry>
            <entry>
                <key>knob3</key>
                <value>0.25</value>
            </entry>
            <entry>
                <key>knob2</key>
                <value>0.25</value>
            </entry>
            <entry>
                <key>knob1</key>
                <value>-0.5</value>
            </entry>
            <entry>
                <key>knob0</key>
                <value>0.25</value>
            </entry>
        </parameters>
        <ports>
            <connected>true</connected>
            <name>sequencer_gate</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>sequencer_out</name>
            <type>OUT</type>
        </ports>
        <posX>2</posX>
        <posY>1</posY>
    </modules>
    <modules>
        <filename>fxml/mixer2.fxml</filename>
        <id>Module4</id>
        <parameters>
            <entry>
                <key>muteVolumeFx2</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>muteVolumeFx1</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>knobVolume2</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>knobVolume1</key>
                <value>0.0</value>
            </entry>
        </parameters>
        <ports>
            <connected>true</connected>
            <name>mixer_input0</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>mixer_input1</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>output</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>mixer_averageOutputValue</name>
            <type>OUT</type>
        </ports>
        <posX>3</posX>
        <posY>0</posY>
    </modules>
    <modules>
        <filename>fxml/vcf-lp.fxml</filename>
        <id>Module5</id>
        <parameters>
            <entry>
                <key>knobCutoff</key>
                <value>1271.2294549958556</value>
            </entry>
            <entry>
                <key>knobResonance</key>
                <value>3.1447251706521424</value>
            </entry>
        </parameters>
        <ports>
            <connected>true</connected>
            <name>vcf_input</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vcf_fm</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>vcf_output</name>
            <type>OUT</type>
        </ports>
        <posX>1</posX>
        <posY>0</posY>
    </modules>
    <modules>
        <filename>fxml/keyboard.fxml</filename>
        <id>Module6</id>
        <parameters/>
        <ports>
            <connected>true</connected>
            <name>outputKeyCV</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>outputKeyGate</name>
            <type>OUT</type>
        </ports>
        <posX>2</posX>
        <posY>0</posY>
    </modules>
    <modules>
        <filename>fxml/oscillo.fxml</filename>
        <id>Module7</id>
        <parameters>
            <entry>
                <key>refreshPeriodSlider</key>
                <value>0.0</value>
            </entry>
        </parameters>
        <ports>
            <connected>true</connected>
            <name>oscillo_in</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>oscillo_out</name>
            <type>OUT</type>
        </ports>
        <posX>4</posX>
        <posY>0</posY>
    </modules>
</configuration>
