<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration>
    <connections>
        <color>0x8a2be2ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module1</idModule>
            <name>vco_inputFm</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module0</idModule>
            <name>outputAmplitude</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0x8a2be2ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module0</idModule>
            <name>vco_inputFm</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module2</idModule>
            <name>rep_out1</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0x8a2be2ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module3</idModule>
            <name>out_input</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module2</idModule>
            <name>rep_out2</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0x8a2be2ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module2</idModule>
            <name>rep_in</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module1</idModule>
            <name>outputAmplitude</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <modules>
        <filename>fxml/vco.fxml</filename>
        <id>Module0</id>
        <parameters>
            <entry>
                <key>octave</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>typeOutput</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>precision</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>choiceBaseFreq</key>
                <value>1.0</value>
            </entry>
            <entry>
                <key>choiceAmplitude</key>
                <value>1.0</value>
            </entry>
        </parameters>
        <ports>
            <connected>true</connected>
            <name>vco_inputFm</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputf0</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputOctave</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputSelectShape</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputAmplitude</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>outputAmplitude</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputSquare</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputSawTooth</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputTriangle</name>
            <type>OUT</type>
        </ports>
        <posX>0</posX>
        <posY>0</posY>
    </modules>
    <modules>
        <filename>fxml/vco.fxml</filename>
        <id>Module1</id>
        <parameters>
            <entry>
                <key>octave</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>typeOutput</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>precision</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>choiceBaseFreq</key>
                <value>1.0</value>
            </entry>
            <entry>
                <key>choiceAmplitude</key>
                <value>1.0</value>
            </entry>
        </parameters>
        <ports>
            <connected>true</connected>
            <name>vco_inputFm</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputf0</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputOctave</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputSelectShape</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputAmplitude</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>outputAmplitude</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputSquare</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputSawTooth</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputTriangle</name>
            <type>OUT</type>
        </ports>
        <posX>1</posX>
        <posY>0</posY>
    </modules>
    <modules>
        <filename>fxml/rep.fxml</filename>
        <id>Module2</id>
        <parameters/>
        <ports>
            <connected>true</connected>
            <name>rep_in</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>rep_out1</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>rep_out2</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>rep_out3</name>
            <type>OUT</type>
        </ports>
        <posX>2</posX>
        <posY>0</posY>
    </modules>
    <modules>
        <filename>fxml/out.fxml</filename>
        <id>Module3</id>
        <parameters>
            <entry>
                <key>muteVolumeFx</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>knobVolume</key>
                <value>0.0</value>
            </entry>
        </parameters>
        <ports>
            <connected>true</connected>
            <name>out_input</name>
            <type>IN</type>
        </ports>
        <posX>3</posX>
        <posY>0</posY>
    </modules>
</configuration>
