<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration>
    <connections>
        <color>0x8a2be2ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module0</idModule>
            <name>out_input</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module7</idModule>
            <name>echo_out</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0x8a2be2ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module1</idModule>
            <name>player_input</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module5</idModule>
            <name>rep_out2</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0x8a2be2ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module6</idModule>
            <name>player_gate</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module3</idModule>
            <name>outputAmplitude</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0x8a2be2ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module4</idModule>
            <name>vco_inputFm</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module2</idModule>
            <name>sequencer_out</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0x8a2be2ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module7</idModule>
            <name>echo_in</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module6</idModule>
            <name>player_output</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0x8a2be2ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module5</idModule>
            <name>rep_in</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module4</idModule>
            <name>outputAmplitude</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <modules>
        <filename>fxml/out.fxml</filename>
        <id>Module0</id>
        <parameters>
            <entry>
                <key>muteVolumeFx</key>
                <value>1.0</value>
            </entry>
            <entry>
                <key>knobVolume</key>
                <value>0.0</value>
            </entry>
        </parameters>
        <ports>
            <connected>true</connected>
            <name>out_input</name>
            <type>IN</type>
        </ports>
        <posX>0</posX>
        <posY>0</posY>
    </modules>
    <modules>
        <filename>fxml/recorder.fxml</filename>
        <id>Module1</id>
        <parameters/>
        <ports>
            <connected>true</connected>
            <name>player_input</name>
            <type>IN</type>
        </ports>
        <posX>1</posX>
        <posY>0</posY>
    </modules>
    <modules>
        <filename>fxml/seq.fxml</filename>
        <id>Module2</id>
        <parameters>
            <entry>
                <key>knob7</key>
                <value>-0.3657079941317515</value>
            </entry>
            <entry>
                <key>knob6</key>
                <value>1.0</value>
            </entry>
            <entry>
                <key>knob5</key>
                <value>0.46874697543651034</value>
            </entry>
            <entry>
                <key>knob4</key>
                <value>0.08758253574027153</value>
            </entry>
            <entry>
                <key>knob3</key>
                <value>-0.4492319475389137</value>
            </entry>
            <entry>
                <key>knob2</key>
                <value>0.15715464667158718</value>
            </entry>
            <entry>
                <key>knob1</key>
                <value>0.6191491370781914</value>
            </entry>
            <entry>
                <key>knob0</key>
                <value>-0.38477577300340315</value>
            </entry>
        </parameters>
        <ports>
            <connected>false</connected>
            <name>sequencer_gate</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>sequencer_out</name>
            <type>OUT</type>
        </ports>
        <posX>2</posX>
        <posY>0</posY>
    </modules>
    <modules>
        <filename>fxml/vco.fxml</filename>
        <id>Module3</id>
        <parameters>
            <entry>
                <key>octave</key>
                <value>4.0</value>
            </entry>
            <entry>
                <key>typeOutput</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>precision</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>choiceBaseFreq</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>choiceAmplitude</key>
                <value>1.0</value>
            </entry>
        </parameters>
        <ports>
            <connected>false</connected>
            <name>vco_inputFm</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputf0</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputOctave</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputSelectShape</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputAmplitude</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>outputAmplitude</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputSquare</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputSawTooth</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputTriangle</name>
            <type>OUT</type>
        </ports>
        <posX>0</posX>
        <posY>1</posY>
    </modules>
    <modules>
        <filename>fxml/vco.fxml</filename>
        <id>Module4</id>
        <parameters>
            <entry>
                <key>octave</key>
                <value>2.0</value>
            </entry>
            <entry>
                <key>typeOutput</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>precision</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>choiceBaseFreq</key>
                <value>2.0</value>
            </entry>
            <entry>
                <key>choiceAmplitude</key>
                <value>1.0</value>
            </entry>
        </parameters>
        <ports>
            <connected>true</connected>
            <name>vco_inputFm</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputf0</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputOctave</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputSelectShape</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputAmplitude</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>outputAmplitude</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputSquare</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputSawTooth</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputTriangle</name>
            <type>OUT</type>
        </ports>
        <posX>1</posX>
        <posY>1</posY>
    </modules>
    <modules>
        <filename>fxml/rep.fxml</filename>
        <id>Module5</id>
        <parameters/>
        <ports>
            <connected>true</connected>
            <name>rep_in</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>rep_out1</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>rep_out2</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>rep_out3</name>
            <type>OUT</type>
        </ports>
        <posX>2</posX>
        <posY>1</posY>
    </modules>
    <modules>
        <filename>fxml/player.fxml</filename>
        <id>Module6</id>
        <parameters/>
        <ports>
            <connected>false</connected>
            <name>Data</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>Amplitude</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>Rate</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>player_output</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>player_gate</name>
            <type>IN</type>
        </ports>
        <posX>3</posX>
        <posY>0</posY>
    </modules>
    <modules>
        <filename>fxml/echo.fxml</filename>
        <id>Module7</id>
        <parameters>
            <entry>
                <key>knobEchoPeriod</key>
                <value>1.6140845279699498</value>
            </entry>
            <entry>
                <key>knobEchoAttenuation</key>
                <value>-1.413247926583356</value>
            </entry>
        </parameters>
        <ports>
            <connected>true</connected>
            <name>echo_in</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>echo_out</name>
            <type>OUT</type>
        </ports>
        <posX>3</posX>
        <posY>1</posY>
    </modules>
</configuration>
