<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration>
    <connections>
        <color>0x8a2be2ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module4</idModule>
            <name>mixer_input0</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module2</idModule>
            <name>outputAmplitude</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0x8a2be2ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module3</idModule>
            <name>oscillo_in</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module1</idModule>
            <name>rep_out1</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0x8a2be2ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module8</idModule>
            <name>vcf_input</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module1</idModule>
            <name>rep_out2</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0x8a2be2ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module7</idModule>
            <name>vco_inputFm</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module7</idModule>
            <name>outputAmplitude</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0x8a2be2ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module4</idModule>
            <name>mixer_input1</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module6</idModule>
            <name>outputAmplitude</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0x8a2be2ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module1</idModule>
            <name>rep_in</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module4</idModule>
            <name>output</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0x8a2be2ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module5</idModule>
            <name>oscillo_in</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module8</idModule>
            <name>vcf_output</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <connections>
        <color>0x8a2be2ff</color>
        <inputPort>
            <connected>true</connected>
            <idModule>Module0</idModule>
            <name>out_input</name>
            <type>IN</type>
        </inputPort>
        <outputPort>
            <connected>true</connected>
            <idModule>Module5</idModule>
            <name>oscillo_out</name>
            <type>OUT</type>
        </outputPort>
    </connections>
    <modules>
        <filename>fxml/out.fxml</filename>
        <id>Module0</id>
        <parameters>
            <entry>
                <key>muteVolumeFx</key>
                <value>1.0</value>
            </entry>
            <entry>
                <key>knobVolume</key>
                <value>0.0</value>
            </entry>
        </parameters>
        <ports>
            <connected>true</connected>
            <name>out_input</name>
            <type>IN</type>
        </ports>
        <posX>0</posX>
        <posY>0</posY>
    </modules>
    <modules>
        <filename>fxml/rep.fxml</filename>
        <id>Module1</id>
        <parameters/>
        <ports>
            <connected>true</connected>
            <name>rep_in</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>rep_out1</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>rep_out2</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>rep_out3</name>
            <type>OUT</type>
        </ports>
        <posX>0</posX>
        <posY>1</posY>
    </modules>
    <modules>
        <filename>fxml/vco.fxml</filename>
        <id>Module2</id>
        <parameters>
            <entry>
                <key>octave</key>
                <value>1.0</value>
            </entry>
            <entry>
                <key>typeOutput</key>
                <value>1.0</value>
            </entry>
            <entry>
                <key>precision</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>choiceBaseFreq</key>
                <value>2.0</value>
            </entry>
            <entry>
                <key>choiceAmplitude</key>
                <value>1.0</value>
            </entry>
        </parameters>
        <ports>
            <connected>false</connected>
            <name>vco_inputFm</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputf0</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputOctave</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputSelectShape</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputAmplitude</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>outputAmplitude</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputSquare</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputSawTooth</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputTriangle</name>
            <type>OUT</type>
        </ports>
        <posX>1</posX>
        <posY>0</posY>
    </modules>
    <modules>
        <filename>fxml/oscillo.fxml</filename>
        <id>Module3</id>
        <parameters>
            <entry>
                <key>refreshPeriodSlider</key>
                <value>0.0</value>
            </entry>
        </parameters>
        <ports>
            <connected>true</connected>
            <name>oscillo_in</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>oscillo_out</name>
            <type>OUT</type>
        </ports>
        <posX>1</posX>
        <posY>1</posY>
    </modules>
    <modules>
        <filename>fxml/mixer2.fxml</filename>
        <id>Module4</id>
        <parameters>
            <entry>
                <key>muteVolumeFx2</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>muteVolumeFx1</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>knobVolume2</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>knobVolume1</key>
                <value>0.0</value>
            </entry>
        </parameters>
        <ports>
            <connected>true</connected>
            <name>mixer_input0</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>mixer_input1</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>output</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>mixer_averageOutputValue</name>
            <type>OUT</type>
        </ports>
        <posX>2</posX>
        <posY>0</posY>
    </modules>
    <modules>
        <filename>fxml/oscillo.fxml</filename>
        <id>Module5</id>
        <parameters>
            <entry>
                <key>refreshPeriodSlider</key>
                <value>0.0</value>
            </entry>
        </parameters>
        <ports>
            <connected>true</connected>
            <name>oscillo_in</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>oscillo_out</name>
            <type>OUT</type>
        </ports>
        <posX>2</posX>
        <posY>1</posY>
    </modules>
    <modules>
        <filename>fxml/vco.fxml</filename>
        <id>Module6</id>
        <parameters>
            <entry>
                <key>octave</key>
                <value>5.0</value>
            </entry>
            <entry>
                <key>typeOutput</key>
                <value>1.0</value>
            </entry>
            <entry>
                <key>precision</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>choiceBaseFreq</key>
                <value>2.0</value>
            </entry>
            <entry>
                <key>choiceAmplitude</key>
                <value>1.0</value>
            </entry>
        </parameters>
        <ports>
            <connected>false</connected>
            <name>vco_inputFm</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputf0</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputOctave</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputSelectShape</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputAmplitude</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>outputAmplitude</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputSquare</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputSawTooth</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputTriangle</name>
            <type>OUT</type>
        </ports>
        <posX>3</posX>
        <posY>0</posY>
    </modules>
    <modules>
        <filename>fxml/vco.fxml</filename>
        <id>Module7</id>
        <parameters>
            <entry>
                <key>octave</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>typeOutput</key>
                <value>1.0</value>
            </entry>
            <entry>
                <key>precision</key>
                <value>0.0</value>
            </entry>
            <entry>
                <key>choiceBaseFreq</key>
                <value>1.0</value>
            </entry>
            <entry>
                <key>choiceAmplitude</key>
                <value>1.0</value>
            </entry>
        </parameters>
        <ports>
            <connected>true</connected>
            <name>vco_inputFm</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputf0</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputOctave</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputSelectShape</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>inputAmplitude</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>outputAmplitude</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputSquare</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputSawTooth</name>
            <type>OUT</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vco_outputTriangle</name>
            <type>OUT</type>
        </ports>
        <posX>5</posX>
        <posY>0</posY>
    </modules>
    <modules>
        <filename>fxml/vcf-lp.fxml</filename>
        <id>Module8</id>
        <parameters>
            <entry>
                <key>knobCutoff</key>
                <value>857.5778762620008</value>
            </entry>
            <entry>
                <key>knobResonance</key>
                <value>1.0</value>
            </entry>
        </parameters>
        <ports>
            <connected>true</connected>
            <name>vcf_input</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>false</connected>
            <name>vcf_fm</name>
            <type>IN</type>
        </ports>
        <ports>
            <connected>true</connected>
            <name>vcf_output</name>
            <type>OUT</type>
        </ports>
        <posX>4</posX>
        <posY>0</posY>
    </modules>
</configuration>
